using Together;
using System.Text.Json;
internal static class BusinessChecks {
    internal static void Run(Action<bool,string> check) {
        check(BusinessMath.Spendable(500,200,1000,0)==300,"working capital is protected even when daily allowance is large");
        check(BusinessMath.Spendable(10000,200,1000,800)==200,"seed and capital reservations share remaining daily allowance");
        check(BusinessMath.Spendable(100,200,1000,0)==0,"insufficient actual cash never uses predicted shipping receipts");
        check(BusinessMath.Settle(1000,800,40)==240,"unused procurement allowance becomes available for reinvestment after verified receipts");
        check(FarmCleanupRules.Allowed("weed","general",false,false)&&FarmCleanupRules.Allowed("stone","roads",false,false),"routine clearing allows weeds and stones in approved areas");
        check(!FarmCleanupRules.Allowed("weed","pasture",false,false)&&!FarmCleanupRules.Allowed("twig","reserve",false,false)&&!FarmCleanupRules.Allowed("stone","woodland",false,false),"pasture woodland and reserves exclude all routine clearing");
        check(!FarmCleanupRules.Allowed("tree","general",true,true)&&!FarmCleanupRules.Allowed("seedling","crop",false,true),"tree clearing needs both land-use permission and explicit task authorization");
        check(FarmCleanupRules.Allowed("seedling","crop",true,true)&&FarmCleanupRules.Allowed("tree","production",true,true),"explicitly approved redevelopment permits young and mature ordinary trees");
        check(!FarmCleanupRules.Allowed("fruit_tree","crop",true,true)&&!FarmCleanupRules.Allowed("grass","production",true,true),"grass and fruit trees never become cleanup debris");
        var cleanup=new FarmCleanupOrder{Id="field",Day=3,Completed=8,CompletedToday=3,DailyLimit=3,Scopes=new(){"zone:field"},PendingPickup=new(){new(3,4)}};
        var persisted=JsonSerializer.Deserialize<FarmCleanupOrder>(JsonSerializer.Serialize(cleanup))!;
        check(FarmCleanupRules.RemainingBudget(persisted)==0&&persisted.Completed==8,"reload preserves cleanup progress and spent daily quota");
        check(persisted.PendingPickup.Single()==new FarmCell(3,4),"reload preserves unfinished loot pickup even when the tree is already gone");
        FarmCleanupRules.NewDay(persisted,3);check(persisted.CompletedToday==3,"same-day retries cannot replenish cleaning quota");
        FarmCleanupRules.NewDay(persisted,4);check(persisted.CompletedToday==0&&persisted.Completed==8&&persisted.Status=="active","next day resumes remaining work without erasing cumulative progress");
        var recurring=new FarmCleanupOrder{Day=1,Recurring=true,Status="complete"};FarmCleanupRules.NewDay(recurring,2);
        check(recurring.Status=="active","daily maintenance rechecks new debris after a clean day");
        var zoneA=new FarmZone{X=2,Y=2,Width=4,Height=4};
        check(FarmCleanupRules.Overlap(zoneA,new(){X=5,Y=5,Width=3,Height=3})&&!zoneA.Contains(new(6,2)),"zone boundaries are half-open and overlap is detected");
        var sites=new[]{new CleanupSite(new(1,0),2),new CleanupSite(new(6,0),2),new CleanupSite(new(2,0),2)};
        bool Open(FarmCell p)=>p.X>=0&&p.X<=7&&p.Y>=0&&p.Y<=3&&!sites.Any(s=>s.Tile==p);
        var route=CleanupRouting.Plan(new(0,0),sites,Open,20,6);
        check(route.Select(s=>s.Site.Tile).SequenceEqual(new[]{new FarmCell(1,0),new FarmCell(2,0),new FarmCell(6,0)}),"cleanup visits the adjacent mixed target before a distant target regardless of input grouping");
        check(CleanupRouting.Plan(new(0,0),sites,Open,4,6).Count==2,"mixed cleanup route stops at the actual total energy budget");
        var wallSites=new[]{new CleanupSite(new(2,1),2),new CleanupSite(new(0,4),2)};
        var aroundWall=CleanupRouting.Plan(new(0,1),wallSites,p=>p.X>=0&&p.X<5&&p.Y>=0&&p.Y<7&&!(p.X==1&&p.Y<6)&&!wallSites.Any(s=>s.Tile==p),20,2);
        check(aroundWall.First().Site.Tile==new FarmCell(0,4),"real walk distance wins over a geometrically closer obstacle behind a wall");
        var allowance=CleanupBudget.Calculate(270,270,30,15,15,0,0);
        check(allowance.FarmEnergy==90&&allowance.Reserve==174&&allowance.Available==94,"cleanup reserves watering, new planting, production and safety before its daily cap");
        check(CleanupBudget.Calculate(170,270,30,15,15,0,0).Available==0,"unfinished farming can eliminate optional cleanup without eliminating other work");
        check(CleanupBudget.Calculate(270,270,30,0,0,94,0).Available==0,"food or a new order cannot replenish spent daily cleanup energy");
        check(CleanupBudget.Calculate(270,270,30,0,0,0,180).Available==0,"three game hours end optional cleanup even with spare stamina");
        check(CleanupBudget.Calculate(270,270,30,0,0,0,0).Available==94,"finishing farming frees reserve but does not remove the daily cleanup cap");
        check(Together.Shared.ForageCropRules.HarvestId(true,"1","")=="(O)399","native spring onion maps to its actual harvest item even with empty crop index");
        check(Together.Shared.ForageCropRules.HarvestId(false,"1","(O)24")=="(O)24"&&Together.Shared.ForageCropRules.HarvestId(true,"2","")=="","normal crops and ginger are not guessed as spring onions");
        check(!Together.Shared.ForageCropRules.CanHarvest(true,"2")&&Together.Shared.ForageCropRules.CanHarvest(true,"1")&&Together.Shared.ForageCropRules.CanHarvest(false,""),"ginger requiring a hoe is not destroyed by an unsupported hand-harvest task");
        check(OperatingMath.CashForSeeds(500,100,1000,200,250)==150,"seeds share delivered cash and approved development reserve");
        check(OperatingMath.GatherDeficit(50,20,15)==15&&OperatingMath.DeliveredDeficit(50,20)==30,"in-transit cargo reduces gathering but cannot be spent before delivery");
        check(OperatingMath.WaterCapacity(24,30,40,0)==0&&OperatingMath.WaterCapacity(24,270,40,24)==48,"farm scale follows available labor and falls back without a partner");
        check(!StorageTiming.NeedsRoom(1,true,false),"one free slot does not trigger an emptying trip");
        check(!StorageTiming.NeedsRoom(0,true,true),"full bag with stack capacity continues gathering");
        check(!StorageTiming.NeedsRoom(0,false,false),"seed-consuming planting does not need an output slot");
        check(StorageTiming.NeedsRoom(0,true,false),"full non-stackable output requires actual unloading");
        check(StorageTiming.DeliveryReason(5,10,false,false)=="","small completed batches do not force companion delivery");
        check(StorageTiming.DeliveryReason(50,10,true,false)!="","delivery is allowed before full when it unlocks approved production");
        check(StorageTiming.DeliveryReason(5,0,false,false)!=""&&StorageTiming.DeliveryReason(5,10,false,true)!="","capacity and end-of-day delivery still run");
        check(AgentNumbers.Read(JsonSerializer.SerializeToElement(new{count="40"}),"count")==40,"integer strings are normalized without changing item identifiers");
        bool badNumber=false;try{AgentNumbers.Read(JsonSerializer.SerializeToElement(new{count="4.5"}),"count");}catch(InvalidOperationException e){badNumber=e.Message=="parameter_requires_integer:count";}
        check(badNumber,"fractional or invalid counts report the exact parameter instead of defaulting");
        var cheap=new BusinessOption("small","machine","a",100,100,100,0,1,"",Array.Empty<string>());
        var large=new BusinessOption("large","building","b",1000,3000,200,0,1,"",Array.Empty<string>());
        var unavailable=cheap with{Id="locked",Gaps=new[]{"missing_native_unlock"},DailyMargin=9999};
        var choices=BusinessMath.Rank(new[]{large,unavailable,cheap},5000,500,10000,0).ToArray();
        check(choices.Length==2&&choices[0].Id=="small","compare capital plus material opportunity cost and exclude unavailable choices");
        check(!BusinessMath.Rank(new[]{cheap with{Existing=1}},500,0,500,0).Any(),"already sufficient capacity does not trigger duplicate investment");
        check(BusinessMath.ProcessingReserve(100,5,2)==10,"raw stock reserves are bounded by actual processing capacity");
        var saved=new FarmBusiness{Enabled=true,ChildGoal="existing-material-goal",ReservedToday=500,Tasks=new(){"paid-order"},Day=3};
        var restored=JsonSerializer.Deserialize<FarmBusiness>(JsonSerializer.Serialize(saved))!;
        check(restored.ReservedToday==500&&restored.Tasks.Single()=="paid-order"&&restored.ChildGoal==saved.ChildGoal,"reload preserves committed budget and pending work for reconciliation");
        check(AgentSchedule.Queueable("player.procure")&&AgentSchedule.Queueable("player.acquire_animal"),"high-level procurement participates in normal persistent queue");
    }
}
