using System.Text.Json;
using System.Text;
using Together;
public static class OperatingLoopChecks {
    private static JsonElement J(object value)=>JsonSerializer.SerializeToElement(value,AgentJson.Options);
    public static void Replay(string directory) {
        int receipts=0,pages=0,max=0;var pending=new List<QueryResult>();
        foreach(string file in Directory.GetFiles(directory,"day-*.jsonl"))foreach(string line in File.ReadLines(file)) {
            using var d=JsonDocument.Parse(line);var root=d.RootElement;if(root.GetProperty("kind").GetString()!="query_completed")continue;
            var q=root.GetProperty("payload").Deserialize<QueryResult>()!;pending.Add(q);receipts++;
            int offset=0;do {var page=J(q.Page(offset,40));int size=ContextBudget.Estimate(page.GetRawText());max=Math.Max(max,size);pages++;if(size>2600)throw new Exception("unbounded receipt page: "+q.Id+" "+size);if(!page.TryGetProperty("next",out var next)||next.ValueKind==JsonValueKind.Null)break;offset=page.GetProperty("next").GetProperty("args").GetProperty("offset").GetInt32();}while(true);
        }
        int batches=0;while(pending.Any(q=>!q.Delivered)) {var p=J(QueryResult.Pending(pending));if(p.GetArrayLength()==0||ContextBudget.Estimate(p.GetRawText())>4200)throw new Exception("pending starvation or overflow");var ids=p.EnumerateArray().Select(q=>q.GetProperty("result_id").GetString()).ToHashSet();foreach(var q in pending.Where(q=>ids.Contains(q.Id)))q.Delivered=true;batches++;}
        Console.WriteLine(AgentJson.Encode(new{receipts,pages,max_page_estimated_tokens=max,delivery_batches=batches,all_delivered=pending.All(q=>q.Delivered)}));
    }
    public static void Run(Action<bool,string> check) {
        string huge=string.Concat(Enumerable.Repeat("原生回执🌱\"\\\n",2000));var q=new QueryResult{Tool="plan.read",Args=J(new{}),Result=J(new{receipt=huge,empty=new{},list=Array.Empty<string>()})};
        int offset=0;var rebuilt=new StringBuilder();bool empty=false,list=false;int largest=0;
        do {var page=J(q.Page(offset,40));largest=Math.Max(largest,ContextBudget.Estimate(page.GetRawText()));foreach(var row in page.GetProperty("fields").EnumerateArray()) {string path=row.GetProperty("path").GetString()!;if(path=="/receipt"){check(row.GetProperty("character_offset").GetInt32()==rebuilt.Length,"receipt fragments have contiguous UTF16 offsets");rebuilt.Append(row.GetProperty("value_fragment").GetString());}if(path=="/empty")empty=row.GetProperty("value").ValueKind==JsonValueKind.Object;if(path=="/list")list=row.GetProperty("value").GetArrayLength()==0;}if(!page.TryGetProperty("next",out var next)||next.ValueKind==JsonValueKind.Null)break;offset=page.GetProperty("next").GetProperty("args").GetProperty("offset").GetInt32();}while(true);
        check(rebuilt.ToString()==huge&&empty&&list&&largest<2600,"bounded pages losslessly preserve giant escaped unicode strings and empty containers");
        string archiveRoot=Path.Combine(Path.GetTempPath(),"operating-query-"+Guid.NewGuid().ToString("N"));
        try {var checkpoint=new MemoryCheckpoint();var archive=new MemoryArchive(archiveRoot,"probe",checkpoint);archive.Append(1,"autoplay","query_completed",AgentJson.Encode(q));var evidence="probe-1:1";check(archive.Query(evidence,q.Id).Result.GetProperty("receipt").GetString()==huge,"stable query evidence restores full result after the live outbox window is pruned");bool badEvidence=false;try{archive.Query(evidence,"different-id");}catch(InvalidOperationException){badEvidence=true;}check(badEvidence,"query evidence cannot be rebound to another result identity");checkpoint.Cursors["probe-1"]=0;badEvidence=false;try{archive.Query(evidence,q.Id);}catch(InvalidOperationException){badEvidence=true;}check(badEvidence,"archived query recovery respects the saved timeline");}finally{if(Directory.Exists(archiveRoot))Directory.Delete(archiveRoot,true);}

        check(ResourceRules.NormalizeGoal("resource","(O)388")=="wood"&&ResourceRules.NormalizeGoal("resource","(O)390")=="stone"&&ResourceRules.NormalizeGoal("resource","(O)771")=="fiber"&&ResourceRules.NormalizeGoal("resource","(O)709")=="hardwood","generic basic resource requests share the existing native work classification");
        check(ResourceRules.NormalizeGoal("resource","(O)378")=="resource"&&ResourceRules.NormalizeGoal("resource","(O)999999")=="resource"&&ResourceRules.NormalizeGoal("fish","(O)388")=="fish","ore routes remain resource work and unknown or different goals are not invented");
        var result=J(new{status="partial",requested=5,completed=2,remaining=3,task_id="fish",command_id="native",intent_id="food",actor="player",stop_reason="target_fish_no_current_window",resume_policy="remaining_only",evidence=huge});
        var summary=ObservationContract.Observation(result,"outcome");check(summary.GetProperty("remaining").GetInt32()==3&&summary.GetProperty("stop_reason").GetString()=="target_fish_no_current_window"&&summary.GetProperty("command_id").GetString()=="native"&&ContextBudget.Estimate(summary.GetRawText())<700,"terminal summary preserves actual quantities, cause and native identity under large evidence");
        var zero=ObservationContract.Observation(J(new{status="partial",requested=5,completed=0,remaining=5,evidence=huge}),"outcome");check(zero.GetProperty("completed").GetInt32()==0&&zero.GetProperty("remaining").GetInt32()==5,"zero progress stays zero after summarization");
        var quote=ObservationContract.Observation(J(new{seed_decision=new{quote_token="native-quote",budget=500,keep_gold=0,candidates=Enumerable.Range(0,25).Select(i=>new{Item="(O)472",Price=20,Growth=4,Maximum=25}),comparison=huge}}),"quote");check(quote.GetProperty("seed_decision").GetProperty("quote_token").GetString()=="native-quote"&&quote.GetProperty("seed_decision").GetProperty("candidates")[0].GetProperty("Price").GetInt32()==20,"asynchronous quote includes token, cash and actual seed comparison");
        var backlog=Enumerable.Range(0,100).Select(i=>new QueryResult{Id="q"+i,Kind=i==99?"outcome":"query",Result=i==99?result:q.Result}).ToArray();var envelope=J(QueryResult.Pending(backlog));check(ContextBudget.Estimate(envelope.GetRawText())<=4200&&envelope[0].GetProperty("result_id").GetString()=="q99"&&backlog.All(q=>!q.Delivered),"bounded backlog prioritizes terminal facts and never marks omitted observations delivered");
        check(QueryResult.IsRead("farm.business_status")&&QueryResult.IsRead("inventory.capacity")&&QueryResult.IsRead("context.read")&&!QueryResult.IsRead("not_a_real.read"),"read tools have explicit metadata including business and capacity");
        check(QueryResult.IsRead("farm.production",J(new{action="coverage"}))&&!QueryResult.IsRead("farm.production",J(new{action="select"}))&&QueryResult.IsRead("farm.business",J(new{})),"polymorphic read actions do not classify mutations as queries");
        var schedule=new AgentSchedule();var future=new AgentTaskSpec{id="social",tool="player.social",not_before=1000};var travel=new AgentTaskSpec{id="travel",tool="player.travel",sequence_after=new(){"social"}};
        schedule.Submit("chain",0,new(){future,travel},4);check(!schedule.Covers("player",4,800)&&schedule.Ready(4,800).Count==0&&schedule.Readiness(schedule.Tasks[0],4,800).Next==1000,"future sequence chain cannot claim actor or suppress independent decisions");
        int delivered=0;schedule.Finished=_=>delivered++;schedule.Finish(schedule.Tasks[0],"partial","native_partial","{}");schedule.Finish(schedule.Tasks[0],"partial","native_partial","{}");check(delivered==1&&schedule.Ready(4,800).Single().spec.id=="travel","terminal delivery is idempotent; ordering dependency releases after partial");
        var dependent=new AgentTaskSpec{id="dependent",tool="player.buy",after=new(){"social"}};schedule.Submit("business",schedule.Revision,new(){dependent},4);schedule.Ready(4,800);check(schedule.Tasks.Last().state=="blocked"&&delivered==2,"business dependency blocks after partial and publishes terminal receipt");
        schedule.CancelPending(new[]{"travel"},"recovery_replaced");check(schedule.Tasks[1].receipt!.Contains("recovery_replaced")&&delivered==3,"cancellation retains actual initiator and uses terminal delivery");
        var rejected=new AgentSchedule{Prepare=_=>throw new InvalidOperationException("closed"),Finished=_=>delivered++};rejected.Submit("blocked",0,new(){new(){id="step",tool="player.service"}},4,retainIndependent:true);check(delivered==4&&rejected.Tasks[0].receipt!.Contains("closed"),"submission preflight failures also deliver a terminal observation");
        check(ModelFailurePolicy.Classify(new InvalidOperationException("context_essential_state_exceeds_budget:20000"))=="local_context_pack"&&ModelFailurePolicy.Classify(new HttpRequestException())=="transport"&&ModelFailurePolicy.Classify(new JsonException())=="response_schema"&&ModelFailurePolicy.Classify(new Exception(),true)=="decision_apply","local context, network, response and application failures stay separate");
        foreach(string kind in new[]{"native_construction_started","native_animal_purchased","native_house_upgrade_started","native_joja_purchase","native_transport_departure","native_geode_opened"})check(NativeCosts.Read(J(new{kind,cost=100})).Single().Amount==100,"native gold expense recognized: "+kind);
        check(NativeCosts.Read(J(new{kind="native_purchase",currency=2,cost=10,trade_item="(O)388",trade_count=5})).All(c=>c.Currency!="gold"),"non-gold currency and barter do not consume gold budget");
        check(!NativeCosts.Read(J(new{kind="expected_shipping",cost=500})).Any(),"expected revenue or arbitrary balance deltas cannot become transaction evidence");
        check(NativeCosts.UnscheduledDevelopment(1000,300)==700&&NativeCosts.UnscheduledDevelopment(1000,1300)==0,"selected development and scheduled same-intent commitment count once");
        check(NativeCosts.PurchaseCap("player.buy",J(new{budget=500,max_unit_price=20,count=3}))==60&&NativeCosts.PurchaseCap("player.build",J(new{budget=1000}))==1000,"cash reservations use bounded purchase or native service cap");
    }
}
